language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.6

before_install:
  - sudo apt-get update -q -y
  - sudo apt-get install libnetcdf-dev -y

script:
  - go install -v ./...
  - test `gofmt -l . | wc -l` = 0
  - go test -v ./...
